- name: update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 600

- name: ensure dependencies are installed
  apt:
    name:
      - apt-transport-https 
      - ca-certificates 
      - curl 
      - gpg
      - jq
    state: present

- name: ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: add kubernetes apt key
  apt_key:
    url: "{{ apt_key_url }}"
    keyring: "/etc/apt/keyrings/kubernetes-apt-keyring.gpg"
    state: present
  register: add_repository_key

- name: add Kubernetes apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] {{ apt_repo_url }} /"
    filename: kubernetes
    state: present
    update_cache: true
    
- name: install kubernetes packages
  apt:
    name: "{{ item }}"
    allow_downgrade: true
    update_cache: yes
    state: present
  loop:
    - kubeadm={{kubeadm_version}} 
    - kubelet={{kubelet_version}} 
    - kubectl={{kubectl_version}} 

- name: hold kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubelet
    - kubectl

- name: ensure kubelet is started and enabled at boot
  service:
    name: kubelet
    state: started
    enabled: true

- include_tasks: setup-control-plane.yml
  when: hostvars[inventory_hostname].tags.Kind == 'master_node'
