- name: update repos
  apt:
    update_cache: yes

- name: update all packages
  apt:
    name: "*"
    state: latest

- name: disable swap for current session
  command: swapoff -a

- name: set vm.swappiness to 0
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    sysctl_set: true
    state: present
    reload: true

- name: "create /etc/modules-load.d/containerd.conf"
  copy:
    dest: "/etc/modules-load.d/containerd.conf"
    content: |
      overlay
      br_netfilter

- name: load modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: let iptables see bridged traffic
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: unloads firewall and disables firewall on boot
  ufw:
    state: disabled