#- name: disable swap for current session
#  command: swapoff -a
#  become: true

- name: set vm.swappiness to 0
  ansible.posix.sysctl:
    name: vm.swappiness
    value: '0'
    sysctl_set: true
    state: present
    reload: true

- name: "create /etc/modules-load.d/containerd.conf"
  copy:
    dest: "/etc/modules-load.d/containerd.conf"
    content: |
      overlay
      br_netfilter

- name: load modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: "create /etc/sysctl.d/99-kubernetes-cri.conf"
  copy:
    dest: "/etc/sysctl.d/99-kubernetes-cri.conf"
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: let iptables see bridged traffic
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: true
    state: present
    reload: true
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward