- name: update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 600

- name: ensure dependencies are installed
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: ensure /etc/apt/keyrings directory exists
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755

- name: add gVisor apt repository key
  get_url:
    url: https://gvisor.dev/archive.key
    dest: /etc/apt/keyrings/gvisor-archive-keyring.asc
    mode: '0644'

- name: add gVisor apt repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/gvisor-archive-keyring.asc] https://storage.googleapis.com/gvisor/releases release main"
    filename: gvisor
    state: present
    update_cache: true

- name: install runsc
  apt:
    name: runsc
    state: present