- hosts: name_master_node
  gather_facts: true
  user: ubuntu
  become: true

  roles:
    #- debug
    - common
    - runsc
    - containerd
    - kubeadm
    - kubeadm-join
    - helm
    - falco
    - fix-ippool

