- name: get the kubeadm join command from the Kubernetes control plane
  command: kubeadm token create --print-join-command
  changed_when: false
  when: hostvars[inventory_hostname].tags.Kind == 'master_node'
  register: kubernetes_join_command_result

- name: set the kubeadm join command globally
  set_fact:
    kubernetes_join_command: >
      {{ kubernetes_join_command_result.stdout }}
    cacheable: true
  when: kubernetes_join_command_result.stdout is defined
  delegate_to: "localhost"
  delegate_facts: true

- name: Print join command
  debug:
    var: hostvars['localhost']['kubernetes_join_command']

- name: Join node to Kubernetes control plane
  shell: >
    {{ hostvars['localhost']['kubernetes_join_command'] }}
    creates=/etc/kubernetes/kubelet.conf
  when: hostvars[inventory_hostname].tags.Kind == 'worker_node'