- name: display all variables/facts known for a host
  ansible.builtin.debug:
    var: hostvars[inventory_hostname].tags.kind

- name: display all variables/facts known for a host
  ansible.builtin.debug:
    var: hostvars[inventory_hostname].tags
  when: hostvars[inventory_hostname].tags.Kind == 'worker_node'

- name: print all available facts
  ansible.builtin.debug:
    var: ansible_facts

- debug:
    msg: "{{ hostvars[inventory_hostname]['kubernetes_join_command'] }}"
